on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 8
      - name: Build with gradle
        run: ./gradlew build dokkaHtml
      - name: Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/html
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*.jar
          name: jars
